name: Workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:

  build_linux:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
    steps:

      - name: "Clone netgen4smesh"
        uses: actions/checkout@v2

      - name: "Fix dependencies"
        run: |
          sudo apt-get install libxext-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/ /usr/lib64

      - name: "Install conda build"
        shell: pwsh
        run: conda install -c conda-forge conda-build

      - name: "Check conda"
        shell: pwsh
        run: |
          conda info -a
          conda list

      - name: "Run conda build"
        shell: pwsh
        run: |
          mkdir conda
          conda build  ci/conda -c conda-forge --output-folder conda

      - name: "Upload conda package"
        uses: actions/upload-artifact@v2
        with:
          name: netgen4smesh-${{ matrix.os }}
          path: conda

  build_win:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
    steps:

      - name: "Clone netgen4smesh"
        uses: actions/checkout@v2

      - name: "Add conda to PATH"
        shell: bash -l {0}
        run: echo "$CONDA/Scripts" >> $GITHUB_PATH

      - name: "Install conda build"
        shell: bash -l {0}
        run: conda install -c conda-forge conda-build

      - name: "Check conda"
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: "Run conda build"
        shell: bash -l {0}
        run: |
          mkdir conda
          source activate
          conda build  ci/conda -c conda-forge --output-folder conda

      - name: "Upload conda package"
        uses: actions/upload-artifact@v2
        with:
          name: netgen4smesh-${{ matrix.os }}
          path: conda

